# supported docker-compose version 1.25.5
version: "3.8"
services:
  vpn-client:
    container_name: docker_torrent_client
    image: spiritsree/docker-torrent-client:latest-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - "9091:9091"
      - "8888:8888"
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /local/data:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      OPENVPN_PROVIDER: 'HideMe'
      OPENVPN_CONNECTION: 'free-ca.hide.me:udp'
      OPENVPN_USERNAME: ''
      OPENVPN_PASSWORD: ''
      TOR_CLIENT_ENABLED: 'false'
      LOCAL_NETWORK: 192.168.1.0/24
    restart: on-failure
    # Below are only for swarm deploy. Ignored for docker-compose up
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  utorrent_container:
    container_name: utorrent_container
    image: spiritsree/docker-client-utorrent:latest
    volumes:
      - /local/data:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - UTORRENT_START_DELAY=45
    network_mode: "service:vpn-client"
    depends_on:
      - vpn-client
