# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Defaults
defaults: &workdirAndImage
  working_directory: ~/workspace

executors:
  docker-executor:
    docker:
      - image: circleci/buildpack-deps:bionic

# Orchestrate or schedule a set of jobs
workflows:
  # Docker image build workflow
  docker-image-build:
    # Run the build job
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code

jobs:
  checkout_code:
    executor: docker-executor
    resource_class: small
    steps:
      - checkout:
          path: ~/workspace/repo
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - repo/

  test:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    executor: docker-executor
    resource_class: small
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run tests
          command: |
            echo "Running tests";
            find . -type f -regex ".*\.sh" | xargs shellcheck --external-sources
          when: always
